"""
YouTube Transcript Processor using youtube-transcript-api

This module provides functionality to load, format, and convert YouTube transcripts to Markdown.
Supports language preferences and available translations.
"""

import logging
import re
from datetime import datetime

try:
    from youtube_transcript_api import YouTubeTranscriptApi
    from langchain_core.documents import Document
except ImportError as e:
    raise ImportError(
        f"Required packages not installed: {e}. Run 'pip install youtube-transcript-api langchain-core'"
    )


class TranscriptProcessor:
    """
    Processor for loading and formatting YouTube transcripts using youtube-transcript-api.

    Handles multiple language preferences, translations, video info, and error cases.
    """

    def __init__(self):
        """
        Initialize the transcript processor.
        """
        self.logger = logging.getLogger(__name__)
        self.api = None

    def load_transcript(
        self,
        youtube_url: str,
        language: list[str] = ["en"],
        translation: str | None = None,
        add_video_info: bool = True,
    ):
        """
        Load transcript using current youtube-transcript-api pattern with fallback.

        Args:
            youtube_url (str): Full YouTube video URL
            language (list[str]): Preferred languages (e.g. ["en", "es"])
            translation (str or None): Translation language if available
            add_video_info (bool): Add video metadata

        Returns:
            list: List of LangChain Document objects with transcripts
        """
        match = re.search(r"(?:v=|\/)([0-9A-Za-z_-]{11})", youtube_url)
        if not match:
            self.logger.error(f"Could not extract video ID from {youtube_url}")
            return []
        video_id = match.group(1)

        try:
            if self.api is None:
                self.api = YouTubeTranscriptApi()
            transcript_obj = None
            # Option A: Simple & recommended for most cases (tries manual first, then auto)
            try:
                transcript_data = self.api.fetch(video_id, languages=language)
                used_lang = (
                    transcript_data[0].get("language", "unknown")
                    if transcript_data
                    else "unknown"
                )
                self.logger.info(f"Fetched transcript in {used_lang} for {youtube_url}")
            except Exception as simple_err:
                self.logger.debug(f"Simple fetch failed: {simple_err}")
                # Option B: More control — list → find → fetch
                transcript_list = self.api.list(video_id)
                available = list(transcript_list)

                if not available:
                    self.logger.warning(f"No transcripts available for {youtube_url}")
                    return []

                transcript_obj = None
                # Try preferred languages (manual > generated by default in find_transcript)
                for lang in language:
                    try:
                        transcript_obj = transcript_list.find_transcript([lang])
                        break
                    except Exception:
                        continue

                # Ultimate fallback: any transcript
                if transcript_obj is None:
                    for t in available:
                        try:
                            transcript_obj = t  # already a Transcript object
                            break
                        except Exception:
                            continue

                if transcript_obj is None:
                    self.logger.warning(
                        f"Could not find usable transcript for {youtube_url}"
                    )
                    return []

                transcript_data = transcript_obj.fetch()
                used_lang = (
                    transcript_data[0].get("language", "unknown")
                    if transcript_data
                    else "unknown"
                )

            # Optional: apply translation if requested and available
            if (
                translation
                and transcript_obj is not None
                and hasattr(transcript_obj, "translate")
                and translation in getattr(transcript_obj, "translation_languages", [])
            ):
                transcript_obj = transcript_obj.translate(translation)
                transcript_data = transcript_obj.fetch()  # re-fetch after translation

            # Format with timestamps (your style)
            content = "\n".join(
                [
                    f"[{int(entry['start'])}s] {entry['text']}"
                    for entry in transcript_data
                ]
            )

            metadata = {
                "source": youtube_url,
                "video_id": video_id,
                "language": used_lang,
            }

            doc = Document(page_content=content, metadata=metadata)
            self.logger.info(f"Successfully loaded transcript for {youtube_url}")
            return [doc]

        except Exception as e:
            self.logger.warning(
                f"Error processing transcript for {youtube_url}: {str(e)}"
            )
            return []

    def _format_transcript(self, docs):
        """
        Format transcript documents with timestamps and content.

        Args:
            docs (list): List of Document objects from YouTube Transcript API

        Returns:
            str: Formatted transcript text
        """
        if not docs:
            return ""

        transcript_lines = []
        for doc in docs:
            lines = doc.page_content.strip().split("\n")
            transcript_lines.extend(line.strip() for line in lines if line.strip())

        return "\n".join(transcript_lines)

    def format_transcript_as_markdown(self, docs, video_info=None):
        """
        Format transcript as Markdown with frontmatter.

        Args:
            docs (list): List of Document objects
            video_info (dict): Video metadata from YouTubePlaylistHandler

        Returns:
            str: Complete Markdown content ready for FileManager.save_markdown()

        Raises:
            ValueError: If no transcript content available
        """
        formatted = self._format_transcript(docs)
        if not formatted:
            raise ValueError("No transcript content to format")

        md = "---\n"
        if video_info:
            md += f"title: {video_info.get('title', 'Unknown Video')}\n"
            md += f"video_id: {video_info.get('video_id', '')}\n"
            md += f"channel_title: {video_info.get('channel_title', '')}\n"
            md += f"published_at: {video_info.get('published_at', '')}\n"
            md += f"youtube_url: https://www.youtube.com/watch?v={video_info.get('video_id', '')}\n"
        md += "source: YouTube Transcript (via youtube-transcript-api)\n"
        md += f"date_extracted: {datetime.now().isoformat()}\n"
        md += "---\n\n"
        md += formatted

        return md
